CREATE TABLE COURSES( NUM_OPERATION NUMBER (4,2) PRIMARY KEY,
   NOM_OPERATION VARCHAR2 (15),
   CATEGORIE VARCHAR2 (10),
   DATE_OPERATION DATE ,
   MONTANT NUMBER (6, 2), 
   SOLDE NUMBER (7, 2) );
