DECLARE 
	CURSOR cours is
	 SELECT * FROM BUDGET WHERE NOM_OPERATION='Courses';
 BEGIN

	FOR cour in cours 
	LOOP
		INSERT INTO COURSES (NUM_OPERATION,NOM_OPERATION,CATEGORIE,	DATE_OPERATION,MONTANT,SOLDE)
		 VALUES (cour.NUM_OPERATION,cour.NOM_OPERATION,cour.CATEGORIE,cour.DATE_OPERATION,cour.MONTANT
		 	,cour.SOLDE);
		-- execute;
	END LOOP;
	Exception 
	When no_data_found then
		NULL; 
	
END;
/