DECLARE
	CURSOR TAB_EUR is 
		SELECT * FROM BUDGET WHERE DATE_OPERATION>'01-jan-2012';
 BEGIN
	FOR row_eur in TAB_EUR LOOP
		INSERT INTO BUDGET_EURO (NUM_OPERATION, NOM_OPERATION, CATEGORIE, DATE_OPERATION, MONTANT, SOLDE) 
			VALUES (row_eur.NUM_OPERATION,row_eur.NOM_OPERATION,row_eur.CATEGORIE,
				row_eur.DATE_OPERATION,(row_eur.MONTANT /11), row_eur.SOLDE);
	END LOOP;

END;
/